{{- if .Values.obs.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "runtime.fullname" . }}
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      runtime.sausheong.io/metrics: "true"
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
{{- end }}
