#!/usr/bin/env bash
# Initialise the cloud-agnostic SECURED overlay for the runtime control plane:
# generate identity secrets, write .env, and select the Caddy TLS mode.
#
#   ./init.sh                      # IP/self-signed (no domain): https on :443
#   ./init.sh runtime.example.com  # real domain: automatic Let's Encrypt cert
#   ./init.sh <domain> --force     # DESTRUCTIVE: see the warning below
#
# --force is not key rotation. It regenerates RUNTIME_SECRETS_KEYS under the
# same "primary" key id, so every secret already sealed with the old key becomes
# undecryptable, and it mints a new bootstrap key. Use it only on a deployment
# with no data worth keeping. Safe rotation adds a NEW key id and re-encrypts;
# see "Key rotation" in identity-and-memory.md.
#
# Turning identity ON requires only RUNTIME_ADMIN_BOOTSTRAP (+ a secrets key);
# OIDC is optional and added by editing .env afterwards (see README).
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$DIR/.env"
TLS_SNIPPET="$DIR/tls.caddy"

DOMAIN=""
FORCE=""
for arg in "$@"; do
  case "$arg" in
    --force) FORCE="--force" ;;
    *) DOMAIN="$arg" ;;
  esac
done

if [[ -f "$ENV_FILE" && "$FORCE" != "--force" ]]; then
  echo "refusing to overwrite existing $ENV_FILE" >&2
  echo "  --force regenerates the secrets key under the SAME 'primary' key id," >&2
  echo "  which leaves already-sealed secrets undecryptable. It is not rotation." >&2
  echo "  To rotate safely, add a new key id: see identity-and-memory.md." >&2
  exit 1
fi
if [[ -f "$ENV_FILE" ]]; then
  echo "WARNING: regenerating $ENV_FILE — secrets sealed with the current key" >&2
  echo "         will become undecryptable." >&2
fi

BOOTSTRAP="$(openssl rand -hex 32)"
KEY_ID="primary"
AES_B64="$(openssl rand -base64 32)"
AGENT_DB_PASSWORD="$(openssl rand -hex 24)"

if [[ -n "$DOMAIN" ]]; then
  # Real domain: Caddy uses automatic public ACME (empty tls block).
  SITE_ADDRESS="$DOMAIN"
  : > "$TLS_SNIPPET"   # empty => public Let's Encrypt
  TLS_MODE="public ACME (Let's Encrypt) for $DOMAIN"
else
  # No domain: bind :443 with Caddy's locally-trusted self-signed cert.
  SITE_ADDRESS=":443"
  echo "tls internal" > "$TLS_SNIPPET"
  TLS_MODE="self-signed (Caddy internal CA) on :443"
fi

cat > "$ENV_FILE" <<EOF
# Generated by deploy/secured/init.sh — DO NOT COMMIT (gitignored).
# Regenerate: ./init.sh [domain] --force
#
# --- Identity (turns runtime identity ON) ---
RUNTIME_ADMIN_BOOTSTRAP=${BOOTSTRAP}
RUNTIME_SECRETS_KEYS=${KEY_ID}:${AES_B64}
RUNTIME_SECRETS_PRIMARY=${KEY_ID}
RUNTIME_AGENT_DB_PASSWORD=${AGENT_DB_PASSWORD}
#
# --- Caddy TLS ---
SITE_ADDRESS=${SITE_ADDRESS}
ACME_EMAIL=admin@example.com
#
# --- OIDC console login (OPTIONAL) ---
# Leave blank to use service-key (paste-token) login. To enable an OIDC IdP
# (Keycloak, Dex, Google, Okta, ...), set all four and recreate runtimed:
# RUNTIME_OIDC_ISSUER=
# RUNTIME_OIDC_CLIENT_ID=
# RUNTIME_OIDC_CLIENT_SECRET=
# RUNTIME_OIDC_REDIRECT_URL=https://${DOMAIN:-YOUR_HOST}/ui/callback
EOF

chmod 600 "$ENV_FILE"
echo "wrote $ENV_FILE"
echo "  identity: ON (bootstrap key + AES secrets key generated)"
echo "  TLS: ${TLS_MODE}"
echo
echo "Your bootstrap superuser key (use it once to seed the first admin, then store safely):"
echo "  ${BOOTSTRAP}"
