#!/usr/bin/env bash
# Generate deploy/compose/.env with fresh secrets for the turnkey stack.
#   RUNTIME_ADMIN_BOOTSTRAP  — superuser break-glass service key
#   RUNTIME_SECRETS_KEYS     — "<id>:<base64-32-byte-key>" for the secrets broker
#   RUNTIME_SECRETS_PRIMARY  — the <id> new secrets seal under (MUST match KEYS)
#   RUNTIME_BROWSER_PROXY_TOKEN — browser egress-proxy credential. The proxy
#                              binds a non-loopback interface so browser
#                              containers on the internal browser-control
#                              network can reach it, which browserd refuses to
#                              do without a >=32-character token.
#   GRAFANA_ADMIN_PASSWORD   — local-only dashboard administrator password
# Refuses to overwrite an existing .env unless --force.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$DIR/.env"
FORCE="${1:-}"

if [[ -f "$ENV_FILE" && "$FORCE" != "--force" ]]; then
  echo "refusing to overwrite existing $ENV_FILE (pass --force to regenerate)" >&2
  exit 1
fi

BOOTSTRAP="$(openssl rand -hex 32)"
KEY_ID="primary"
AES_B64="$(openssl rand -base64 32)"
GRAFANA_PASSWORD="$(openssl rand -hex 24)"
AGENT_DB_PASSWORD="$(openssl rand -hex 24)"
BROWSER_PROXY_TOKEN="$(openssl rand -hex 32)"

cat > "$ENV_FILE" <<EOF
# Generated by deploy/compose/init.sh — DO NOT COMMIT (gitignored).
# Regenerate with: make compose-init FORCE=--force
RUNTIME_ADMIN_BOOTSTRAP=${BOOTSTRAP}
RUNTIME_SECRETS_KEYS=${KEY_ID}:${AES_B64}
RUNTIME_SECRETS_PRIMARY=${KEY_ID}
RUNTIME_AGENT_DB_PASSWORD=${AGENT_DB_PASSWORD}
RUNTIME_BROWSER_PROXY_TOKEN=${BROWSER_PROXY_TOKEN}
GRAFANA_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
DOCKER_GID=999
EOF

chmod 600 "$ENV_FILE"
echo "wrote $ENV_FILE (bootstrap, AES, browser-proxy, and Grafana credentials generated)"
