#!/usr/bin/env bash
# Generate deploy/compose/.env with fresh secrets for the turnkey stack.
#   RUNTIME_ADMIN_BOOTSTRAP  — superuser break-glass service key
#   RUNTIME_SECRETS_KEYS     — "<id>:<base64-32-byte-key>" for the secrets broker
#   RUNTIME_SECRETS_PRIMARY  — the <id> new secrets seal under (MUST match KEYS)
# Refuses to overwrite an existing .env unless --force.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$DIR/.env"
FORCE="${1:-}"

if [[ -f "$ENV_FILE" && "$FORCE" != "--force" ]]; then
  echo "refusing to overwrite existing $ENV_FILE (pass --force to regenerate)" >&2
  exit 1
fi

BOOTSTRAP="$(openssl rand -hex 32)"
KEY_ID="primary"
AES_B64="$(openssl rand -base64 32)"

cat > "$ENV_FILE" <<EOF
# Generated by deploy/compose/init.sh — DO NOT COMMIT (gitignored).
# Regenerate with: make compose-init FORCE=--force
RUNTIME_ADMIN_BOOTSTRAP=${BOOTSTRAP}
RUNTIME_SECRETS_KEYS=${KEY_ID}:${AES_B64}
RUNTIME_SECRETS_PRIMARY=${KEY_ID}
EOF

chmod 600 "$ENV_FILE"
echo "wrote $ENV_FILE (bootstrap key + AES secrets key generated)"
